Repository echobind/react-native-template, pull requests merged in 2019-09, with the labels that each got.

#63 Update Dependencies
  Gemfile.lock
  dependencies.json
  devDependencies.json
  src/App.tsx
  src/config/reactotron/index.ts
  src/config/reactotron/reactotron.ts
Labels: chore

#67 fix: update rnpm
  devDependencies.json
  react-native.config.js
  setup/index.js
  setup/rnpm.json
Labels: chore

#70 feat: update docs
  LICENSE.md
  README.md
Labels: docs

#56 refactor(project_setup): remove detox,circleci,fastlane config in favor of templates via hygen
  .circleci/config.yml
  README.md
  android/Gemfile
  android/fastlane/Appfile
  android/fastlane/Fastfile
  android/fastlane/Pluginfile
  docs/circle-ci.md
  docs/hygen-templates.md
  e2e/IntroScreen.spec.js
  e2e/config.json
  e2e/init.js
  ios/Gemfile
  ios/Matchfile
  ios/fastlane/Fastfile
  ios/fastlane/Pluginfile
  setup/detox.json
  setup/index.js
  setup/scripts.json
Labels: enhancement

#57 (RA) Updating the template for more configurability
  README.md
  _templates/setup/splashscreen/android/MainActivity.ejs.t
  _templates/setup/splashscreen/android/MainActivityImport1.ejs.t
  _templates/setup/splashscreen/android/MainActivityImport2.ejs.t
  _templates/setup/splashscreen/android/colors.xml.ejs.t
  _templates/setup/splashscreen/android/copyImagesToMipMaps.ejs.t
  _templates/setup/splashscreen/android/disableWindowPreview.ejs.t
  _templates/setup/splashscreen/android/launch_screen.xml.ejs.t
  _templates/setup/splashscreen/android/styles.xml.ejs.t
  _templates/setup/splashscreen/ios/AppDelegate1.ejs.t
  _templates/setup/splashscreen/ios/AppDelegate2.ejs.t
  _templates/setup/splashscreen/ios/LaunchScreen.xib.ejs.t
  _templates/setup/splashscreen/ios/copySplashIconImageset.ejs.t
  dependencies.json
  setup/index.js
Labels: enhancement

#78 feat(environment): add solidarity to ensure dependencies are installed.
  .node-version
  .solidarity
  README.md
  devDependencies.json
  setup/index.js
Labels: enhancement
